name: Team Michael's approval workflow
on: pull_request_review

jobs:
  labelWhenApproved:
    steps:
    - name: Label when approved
      uses: pullreminders/label-when-approved-action@master
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "approved"
      
    runs-on: ubuntu-latest
